INSERT INTO songs (group_name, song_name, release_date, text, link) VALUES
('Muse', 'Supermassive Black Hole', '2006-07-16', 'Ooh baby, don''t you know I suffer?\nOoh baby, can you hear me moan?\nYou caught me under false pretenses\nHow long before you let me go?\n\nOoh\nYou set my soul alight', 'https://www.youtube.com/watch?v=Xsp3_a-PMTw'),
('The Beatles', 'Hey Jude', '1968-08-26', 'Hey Jude, don''t make it bad\nTake a sad song and make it better\nRemember to let her into your heart\nThen you can start to make it better', 'https://www.youtube.com/watch?v=A_MjCqQoLLA'),
('Queen', 'Bohemian Rhapsody', '1975-10-31', 'Is this the real life? Is this just fantasy?\nCaught in a landslide, no escape from reality\nOpen your eyes, look up to the skies and see\nI''m just a poor boy, I need no sympathy', 'https://www.youtube.com/watch?v=fJ9rUzIMcZQ'),
('Led Zeppelin', 'Stairway to Heaven', '1971-11-08', 'There''s a lady who''s sure all that glitters is gold\nAnd she''s buying a stairway to heaven\nWhen she gets there she knows, if the stores are all closed\nWith a word she can get what she came for', 'https://www.youtube.com/watch?v=QkF3oxziUI4'),
('Pink Floyd', 'Comfortably Numb', '1979-11-30', 'Hello? Is there anybody in there?\nJust nod if you can hear me\nIs there anyone home?\nCome on now, I hear you''re feeling down\nWell, I can ease your pain', 'https://www.youtube.com/watch?v=_FrOQC-zEog'),
('Nirvana', 'Smells Like Teen Spirit', '1991-09-10', 'Load up on guns, bring your friends\nIt''s fun to lose and to pretend\nShe''s over bored and self assured\nOh no, I know a dirty word', 'https://www.youtube.com/watch?v=hTWKbfoikeg'),
('Radiohead', 'Creep', '1992-09-21', 'When you were here before\nCouldn''t look you in the eye\nYou''re just like an angel\nYour skin makes me cry\nYou float like a feather\nIn a beautiful world', 'https://www.youtube.com/watch?v=XFkzRNyygfk'),
('The Rolling Stones', 'Paint It Black', '1966-05-13', 'I see a red door and I want it painted black\nNo colors anymore, I want them to turn black\nI see the girls walk by dressed in their summer clothes\nI have to turn my head until my darkness goes', 'https://www.youtube.com/watch?v=O4irXQhgMqg'),
('David Bowie', 'Space Oddity', '1969-07-11', 'Ground Control to Major Tom\nTake your protein pills and put your helmet on\nCommencing countdown, engines on\nCheck ignition and may God''s love be with you', 'https://www.youtube.com/watch?v=iYYRH4apXDo'),
('U2', 'With or Without You', '1987-03-16', 'See the stone set in your eyes\nSee the thorn twist in your side\nI''ll wait for you\nSleight of hand and twist of fate\nOn a bed of nails, she makes me wait', 'https://www.youtube.com/watch?v=XmSdTa9kaiQ');
