openapi: 3.0.3
info:
  title: Music Info API
  version: 0.0.1
servers:
  - url: http://external-api
paths:
  /info:
    get:
      summary: Get song details
      description: Returns enriched information about a song (release date, lyrics, link).
      parameters:
        - name: group
          in: query
          required: true
          schema:
            type: string
          example: "Muse"
        - name: song
          in: query
          required: true
          schema:
            type: string
          example: "Supermassive Black Hole"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SongDetail"
        "400":
          description: Bad request (e.g., missing parameters)
        "500":
          description: Internal server error
components:
  schemas:
    SongDetail:
      type: object
      required:
        - releaseDate
        - text
        - link
      properties:
        releaseDate:
          type: string
          format: date
          example: "16.07.2006"
        text:
          type: string
          example: |
            Ooh baby, don't you know I suffer?
            Ooh baby, can you hear me moan?
        link:
          type: string
          example: "https://www.youtube.com/watch?v=Xsp3_a-PMTw"
